#+TITLE: Ethics debate vs Finntronaut

* Notes
** Homesteading
Homesteading is defined as the original appropriation of a scarce nature-given good. Ownership is pre-supposed as being different to mere possession by both parties in a dispute, which implies that late-comers cannot be the owners of a property, if they were then we would be back to mere possession which contradicts ownership not being possession.

Furthermore it would be impossible to do anything if late-comers had an equal say over the use of a property as the first-comer, as before the first-comer could begin using the nature-given good for anything he would have to wait for permission of every late-comer, which is a set of indeterminate size that may include people who are yet to be born.

Abandonment of priority to the first-comer would also run contrary to the conflict-avoiding nature of argumentation and the very purpose of property rights in the first place. This is because priority given to the late-comer is by definition a conflict-initiation norm---it is a norm that supposses those who are initiating the conflict get priority in a dispute over property rights.
** What are rights
** The Necessity for Law and thus Property Rights
#+begin_quote
As long as scarcity and hence potential interpersonal conflict exists, every society requires a well-defined set of property rights assignments.
#+end_quote
--- Hans-Hermann Hoppe, /The Ethics of Liberty/ p. xiii
+ the law assigns property
+ by the very fact that one is engaging in any ethical deliberation (or any deliberation at all), it is implied that one need concern oneself with scarcity, at the very least of the means implemented in the deliberation, and of appropriation, at the very least of the means one must appropriate to make the ethical deliberation.
*** The purpose of a human ethic
#+begin_quote
In fact, Rawls, to whom the philosophy profession has in the meantime accorded the rank of the premier ethicist of our age, was the prime example of someone completely uninterested in what a human ethic must accomplish: that is, to answer the question of what I am permitted to do right now and here, given that I cannot not act as long as I am alive and awake and the means or goods which I must employ in order to do so are always scarce, such that there may be interpersonal conflicts regarding their use.
#+end_quote
--- Hans-Hermann Hoppe, /The Ethics of Liberty/ p. xiv
+ cannot act, and hence remain alive, without the use of scarce means, that scarcity raising the possibility of conflict over those means
+ A human ethic has 2 properties it must satisfy:
  1. universalisation---applies to all mankind
  2. assures the survival of mankind (no point in concerning yourself with a human ethic if no humans are alive)
**** Argumentum e Contrario
If it is not the case that a person A was the owner of his body and all goods appropriated by him two possibilities remain:
1. another person, B, is the owner of A and all goods appropriated by A
2. all things are universally co-owned, A and B are equal owners of each other and all goods aquired by either party.

(1) fails on the grounds of not being a universal ethic---it describes a society of two distinct classes; humans and sub-humans

(2) fails on two separate grounds:
a. it would lead to the extinction of humanity as in order to act one would have to ask everyone else for permission to act, which is itself an action, meaning no action could occur.
b. co-ownership itself is impossible, as it cannot handle disputes over the co-owned means.

** What is science
Science refers to a systematic enterprise that builds and organizes knowledge, and the set of knowledge produced by this enterprise.[fn:1]
*** Definitions
**** Merriam-Webster[fn:2]
1.
   a. knowledge or a system of knowledge covering general truths or the operation of general laws especially as obtained and tested through scientific method
   b. such knowledge or such a system of knowledge concerned with the physical world and its phenomena (ex:natural science)
2.
   a. a department of systematized knowledge as an object of study (ex:the scicence of theology)
   b. something (such as a sport or technique) that may be studied or learned like systematized knowledge (ex:I have it down to a science)
3. a system or method reconciling practical ends with scientific laws (ex:cooking is both a science and an art)
4. the state of knowing---knowledge as distinguished from ignorance or misunderstanding

** Argumentation Ethics
*** What is argumentation
Argumentation is an interaction wherein two or more parties assert premises in support of two or more contradictory conclusions, with the goal of each party being to find what the correct conclusion is. Argumentation is specifically the method of solving disputes over claims of truth through the use of peaceful means, that is one tries to convince their interlocutor through the force of their argument, not by aggressing upon them.

The ideological salesman is in the business of persuading his opponents of his own conclusion, without paying any mind to what the truth of the matter is.

*** Ethic only applies during argumentation
+ inconsistent system of ethics, therefore false
  + argumentation does not turn an irrational animal into a rational one (a person)
Argumentation must take place between people, i.e. rational animals or actors. The fact that B deciding to engage in argumentation with A does not turn A into a person where before he was some beast incapable of action, it follows that this is an inconsistent system of ethics---in one moment the adherent asserts the ethic of liberty and the next some negation of it. Inconsistency is by definition contradictiory---to dispute this is to say that one may remain consistent in the ethic of non-aggression where they only aggress on a person in one location in spacetime but dont aggress on others in different locations in spacetime, which is an absurdity.
*** Universalisation
+ ask him if hes a particularist, can divert into [[Argumentum e Contrario]] here
Argumentation takes for granted that the rules we live by are universal because argumentation involves not violent attacks, but peaceful exchanges of propositions with the goal being to accept the truth should it be demonstrated. Therefore any argument we offer has to, in principle, be acceptable to all people. Lets take the example of A wishing to argue that he should be able to aggress against B, it would be impossible for A to convince B to go along with this, by the definition of aggression. You cannot consent to crime. Therefore, to get B to acquiesce to this norm A is stuck not with argumentation, i.e. rational justification, but with violence.
*** Examples of impossible arguments
+ "nobody should be allowed to use scarce means"
*** modus tollens argument
/Modus tollens/ is:
1. $p \implies q$
2. $\neg p$
3. $\therefore \neg q$

"if p implies q and q is not true, p must not be true," we can apply this to argumentation ethics as follows (A=/I ought to own that which I originally appropriate/, B=/I ought to preserve life/):
1. $\neg B\implies \text{performatory self-contradiction}$
2. $\therefore (\neg(\neg B))$
3. $\therefore B$
4. $\neg A\implies\neg B$
5. $\neg(\neg B)\implies\neg(\neg A)$ /modus tollens on 4/
6. $B\implies A$
7. $A$

In words, the claim that you ought not live ($\neg B$) is a dialectic contradiction, therefore you ought to preserve your own life, the anti-homestead ethic implies the anti-life ethic, therefore via modus tollens, the negation of the anti-life ethic implies the negation of the anti-homestead ethic, so a life-ethic implies a homestead ethic. As an anti-life ethic is dialectically false, an anti-homestead ethic is also dialectically false.
** Estoppel
B aggresses on A, for A to object to retribution, he must engage in discourse with B, that is he must at least temporarily adopt the stance of a peaceful, civilised person in trying to persuade A, through reason and consistent, universal principles, of why A should not punish him. This means that B is claiming that A should not perform the retribution on B, meaning that he thinks this action is unjust. But that retribution specifically mirrors the prior action of B, meaning he thinks it is a proper thing to be done. Therefore B could not make this claim without contradicting himself, meaning he cannot object.
** The self-defeat of rights-sceptics
If A has a right to X, this means that he is allowed to enforce him doing X. If a rights-sceptic claims that A has no such right, it either means that he thinks others have a right to enforce that A not do X, or that nobody has a right to enforce anything. The former fails on contradicting the belief of the rights sceptic that nobody is allowed to enforce anything, the latter fails on the grounds that the rights-sceptic cannot have an objection to A enforcing his right to X, as he himself claims that he has no right to enforce that A not do X.

** Useful SEP pages
*** Justice https://plato.stanford.edu/entries/justice/
+ "The idea of justice occupies centre stage both in ethics, and in legal and political philosophy."
*** The Nature of Law https://plato.stanford.edu/entries/lawphil-nature/
+ "Law, however, is also a normative social practice: it purports to guide human behavior, giving rise to reasons for action."
*** Natural Law Theories https://plato.stanford.edu/entries/natural-law-theories/
+ "The fulcrum and central question of natural law theories of law is: How and why can law, and its positing in legislation, judicial decisions, and customs, give its subjects sound reason for acting in accordance with it?"

* flow
+ it has to be stated that argumentation cannot exist in a normative void... one could not argue that argumentation is pointless
  + violation of humes
    + saying that you are not speaking is dialectic contradiction
    + think you ought speak is a subjective belief
      + grass ought to be green is of a different type
        +
+ semantic point of whether lnc "applies"
  + first if it is true that the conclusions only matter in argumentation... that applies to all conclusions
    + the proof is of the same sort, the negation doesnt make sense
      + I ought not ever speak
        + we have that speech presupposes that you ought to speak
          +
        + determinism---if you go back far enough you realise that the preferences that you have you did not prefer to have those preferences
          + you did ought to choose it
        + could believe that fav team ought win the championship
          +
+ triple logic
  + how do we determine the correct system of logic to implement in a given scenario
    +
+ definition of argumentation too strict
  + argumentation is not just free-floating propositions
    + devils advocate
      +
+ getting to the truth
  + what would it mean to say that argumentation need not be peaceful... violently attacking the opponent to get at truth
    + rhetoritician who is very good at peddling falsehoods
      + I know that I dont know
        + how do you know they are false
          +
+ definition of argumentation is unspecified---can one put a hierarchy on the qualifications for arguing
  + cant put
    + then contradictory norms in argumentation
      + desire for agreement getting both parties further away from the truth
      + peaceful means getting in the way of getting at agreement
+ not arguing because hasnt accepted presuppositions
  + truth
    +
  + agreement
    + what?
      +
+ not clear which sect of libertarianism AE implies if any
  + sects of libertism that contradict each other
    + two incompatible NAP's
      +
+ leap from pacifistic argumentation to non-aggressive
  + no violence in argumentation, therefore no self-defence
    + peaceful dispute resolution
+ action axiom makes it possible for one to follow the NAP when they prefer to aggress
  + this makes virtue impossible because cannot violate
+ self interest---some christians who want to convert others but they say that those who are not aware will go to heaven so they do a disservice to others, similar to AE, people are better off serving their self-interest than if they are converted
  +
* Footnotes

[fn:1]https://www.wikidata.org/wiki/Q336 (https://archive.ph/Blr6n)

[fn:2]https://www.merriam-webster.com/dictionary/science (https://archive.ph/TQoHB)
