#+TITLE: Socialism vs Capitalism debate

* Notes
** Homesteading
Homesteading is defined as the original appropriation of a scarce nature-given good. Ownership is different to mere possession, which implies that late-comers cannot be the owners of a property, if they were then we would be back to mere possession which contradicts ownership not being possession.

Furthermore it would be impossible to do anything if late-comers had an equal say over the use of a property as the first-comer, as before the first-comer could begin using the nature-given good for anything he would have to wait for permission of every late-comer, which is a set of indeterminate size that may include people who are yet to be born.

Abandonment of priority to the first-comer would also run contrary to the conflict-avoiding nature of argumentation and the very purpose of property rights in the first place. This is because priority given to the late-comer is by definition a conflict-initiation norm---it is a norm that supposses those who are initiating the conflict get priority in a dispute over property rights.
** What are rights
** The Necessity for Law and thus Property Rights
#+begin_quote
As long as scarcity and hence potential interpersonal conflict exists, every society requires a well-defined set of property rights assignments.
#+end_quote
--- Hans-Hermann Hoppe, /The Ethics of Liberty/ p. xiii
+ the law assigns property
+ by the very fact that one is engaging in any ethical deliberation (or any deliberation at all), it is implied that one need concern oneself with scarcity, at the very least of the means implemented in the deliberation, and of appropriation, at the very least of the means one must appropriate to make the ethical deliberation.
*** The purpose of a human ethic
#+begin_quote
In fact, Rawls, to whom the philosophy profession has in the meantime accorded the rank of the premier ethicist of our age, was the prime example of someone completely uninterested in what a human ethic must accomplish: that is, to answer the question of what I am permitted to do right now and here, given that I cannot not act as long as I am alive and awake and the means or goods which I must employ in order to do so are always scarce, such that there may be interpersonal conflicts regarding their use.
#+end_quote
--- Hans-Hermann Hoppe, /The Ethics of Liberty/ p. xiv
+ cannot act, and hence remain alive, without the use of scarce means, that scarcity raising the possibility of conflict over those means
+ A human ethic has 2 properties it must satisfy:
  1. universalisation---applies to all mankind
  2. assures the survival of mankind (no point in concerning yourself with a human ethic if no humans are alive)
**** Argumentum e Contrario
If it is not the case that a person A was the owner of his body and all goods appropriated by him two possibilities remain:
1. another person, B, is the owner of A and all goods appropriated by A
2. all things are universally co-owned, A and B are equal owners of each other and all goods aquired by either party.

(1) fails on the grounds of not being a universal ethic---it describes a society of two distinct classes; humans and sub-humans

(2) fails on two separate grounds:
a. it would lead to the extinction of humanity as in order to act one would have to ask everyone else for permission to act, which is itself an action, meaning no action could occur.
b. co-ownership itself is impossible, as it cannot handle disputes over the co-owned means.

** What is science
Science refers to a systematic enterprise that builds and organizes knowledge, and the set of knowledge produced by this enterprise.[fn:1]
*** Definitions
**** Merriam-Webster[fn:2]
1.
   a. knowledge or a system of knowledge covering general truths or the operation of general laws especially as obtained and tested through scientific method
   b. such knowledge or such a system of knowledge concerned with the physical world and its phenomena (ex:natural science)
2.
   a. a department of systematized knowledge as an object of study (ex:the scicence of theology)
   b. something (such as a sport or technique) that may be studied or learned like systematized knowledge (ex:I have it down to a science)
3. a system or method reconciling practical ends with scientific laws (ex:cooking is both a science and an art)
4. the state of knowing---knowledge as distinguished from ignorance or misunderstanding

** Argumentation Ethics
*** What is argumentation
Argumentation is an interaction wherein two or more parties assert premises in support of two or more contradictory conclusions, with the goal of each party being to find what the correct conclusion is. Argumentation is specifically the method of solving disputes over claims of truth through the use of peaceful means, that is one tries to convince their interlocutor through the force of their argument, not by aggressing upon them.

The ideological salesman is in the business of persuading his opponents of his own conclusion, without paying any mind to what the truth of the matter is.

*** Ethic only applies during argumentation
+ inconsistent system of ethics, therefore false
  + argumentation does not turn an irrational animal into a rational one (a person)
Argumentation must take place between people, i.e. rational animals or actors. The fact that B deciding to engage in argumentation with A does not turn A into a person where before he was some beast incapable of action, it follows that this is an inconsistent system of ethics---in one moment the adherent asserts the ethic of liberty and the next some negation of it. Inconsistency is by definition contradictiory---to dispute this is to say that one may remain consistent in the ethic of non-aggression where they only aggress on a person in one location in spacetime but dont aggress on others in different locations in spacetime, which is an absurdity.
*** Universalisation
+ ask him if hes a particularist, can divert into [[Argumentum e Contrario]] here
Argumentation takes for granted that the rules we live by are universal because argumentation involves not violent attacks, but simply persuasion. Therefore any argument we offer has to, in principle, be acceptable to all people. Lets take the example of A wishing to argue that he should be able to aggress against B, it would be impossible for A to convince B to go along with this, by the definition of aggression. You cannot consent to crime. Therefore, to get B to acquiesce to this norm A is stuck not with argumentation, i.e. rational justification, but with violence.
*** Examples of impossible arguments
+ "nobody should be allowed to use scarce means"
*** modus tollens argument
/Modus tollens/ is:
1. $p \implies q$
2. $\neg p$
3. $\therefore \neg q$

"if p implies q and q is not true, p must not be true," we can apply this to argumentation ethics as follows (A=/I ought to own that which I originally appropriate/, B=/I ought to preserve life/):
1. $\neg B\implies \text{performatory self-contradiction}$
2. $\therefore (\neg(\neg B))$
3. $\therefore B$
4. $\neg A\implies\neg B$
5. $\neg(\neg B)\implies\neg(\neg A)$ /modus tollens on 4/
6. $B\implies A$
7. $A$

In words, the claim that you ought not live ($\neg B$) is a dialectic contradiction, therefore you ought to preserve your own life, the anti-homestead ethic implies the anti-life ethic, therefore via modus tollens, the negation of the anti-life ethic implies the negation of the anti-homestead ethic, so a life-ethic implies a homestead ethic. As an anti-life ethic is dialectically false, an anti-homestead ethic is also dialectically false.
** Estoppel
B aggresses on A, for A to object to retribution, he must engage in discourse with B, that is he must at least temporarily adopt the stance of a peaceful, civilised person in trying to persuade A, through reason and consistent, universal principles, of why A should not punish him. This means that B is claiming that A should not perform the retribution on B, meaning that he thinks this action is unjust. But that retribution specifically mirrors the prior action of B, meaning he thinks it is a proper thing to be done. Therefore B could not make this claim without contradicting himself, meaning he cannot object.
** The self-defeat of rights-sceptics
If A has a right to X, this means that he is allowed to enforce him doing X. If a rights-sceptic claims that A has no such right, it either means that he thinks others have a right to enforce that A not do X, or that nobody has a right to enforce anything. The former fails on contradicting the belief of the rights sceptic that nobody is allowed to enforce anything, the latter fails on the grounds that the rights-sceptic cannot have an objection to A enforcing his right to X, as he himself claims that he has no right to enforce that A not do X.

* flow
+ Ethic of slavery or ethic of self ownership?
+ tradgedy of commons
  + most systems agree that conflicts are a bad thing
    + any non-NAP ethic authorises conflict
      + crusoe gets stick, puts stick down
        + someone else picks up
          + PoC is whether individual can lose property rights if it goes beyond their means to use, only extend to that which they can make use of
            + property rights come from social cohesion as opposed to individuals
              + if interests of any given party are not respected then the social fabric of society requires a material equilibrium to be established
                + in the case of use I mean towards some end, that end can be established
                  + unjustifiable non-aggression like suicide
                    + slave morality
                      + PoC is definition of description of will
                        + I suspect it isnt
                          + what is PP's system?
                            + material conditions have reached a deficit and you can fix this but you dont then you dont own the private property
                              + this is expression of will, arent necessarily different, not distinct wills?
                                + for the same reason its fine to stop
                                  + private property based on mutual respect
                                    + aggression is the initiation of conflict
                                      + it is preserving the will of the sandwich hoarder to take his sandwiches
                                        + is it possible to will that a bunch of sandwiches mould?
                                          + depends on
                                            + completeness, natural law aiming at some perfect will
+ rational
  + logical judgement free of contradiction
    + apply to law
      + basis of justice and epistemology, ethically necessary, necessary for any ethic to attain truth value
      + when it starts impeding the wellbeing of themselves or others then its considered insanity---they have to live a fulfilling life
        + how do we determine this? Personal preference?
          + look whether its impeding their actions in life
            + so are you allowed to prevent people from uttering contradictions?
              + are you allowed to prevent people from acting immorily
                + yes, but dont produce more immoral action
                  + what is the definition of immorality
                    + against the expression of natural will
                      + how do we determine natural will?
                        + ban on self-destructive behaviour
                          + cant force moral progression on tribesmen
                            + unless it leads to the tribesmen deaths
                              + analogous to FGM and slavery he says
                                + when is it that we are allowed to force moral progression
                                  + its about respective individuals interests, impedes upon the expression of an individuals will---all irrational behaviour?
                                    + allowed to force moral progression when people are being irrational?---when an individual is being irrational at an ideological level you meet them at that level, when they are irrational at a concrete level, at an authoritative level its
+ what irrational behaviours am I allowed to prevent
  + based on activity, whether bringing harm to self or others
    + I thought all irrational behaviour brings harm to yourself?
      + so then why cant I stop all irrational behaviour---dont perpetuate more disrespect
        + how do we know when its causing more disrespect?
          + how are you determining that it would be fine to take food but not fine to tie up the rain dancers and give them a lecture on meterology
            + interpersonal comparison of utility
              + not allowed to do literally anything to preserve a persons life---starving man will not be able to actualise teleological goal if he dies so you can take food from food
                + if you perpetuate a greater disjunction in teleological collective then you are perpetuating more harm
                  + legal limitation---the reason we engage in certain rights in the first place is because
                    + why fine to take food but not kidney
                      + autonomy---it wouldnt be rational to take the kidney
                        +
                      + there is rational and irrational risk
                        + how do we divide rational from irrational risk
                          + irrational risk to take kidney but not food?
                            + irrational to take kidney and food
                              + less irrational to take food
                                + respecting more rights of both parties than if you denied the food?
                                  + respecting both parties right to life, respecting both parties right to wellbeing, right to be punished
                                    + the food man will be worse off without the food, his right to wellbeing is being violated
                                      + not as violated as if the guy died
                                        + the wellbeing of everyone is reduced more if guy dies
                                          + how do we determine the wellbeing of everyone
                                            + give me the derivation rather than how to make such a derivation
                                              +
                            + consider everyones interests, maximise end teleological goal, all parties in principle can actually engage and understand the failure of their reasoning---a tragedy where the legal structure of our society is placing an individual as being alienated from the universality of the state, forced to be criminal or disrespect themselves
  + force people to give up means---peter singer reductio
+ taxation is theft
+ two forces that are qualitatively different but quantitatively equal
  + example for a crime with a punishment that is qualitatively different but quantitatively equal
    + individual has lost from theft an amount where they had to work 5 months, then you can imprison theif for 5 months
      + what makes these equal?
        + relies on the assumption that they value their time equally
          + covert interpersonal comparison of utility
            + arbitrary standard to compare the value of the time of both parties to some random valuation
              + against someones subjectivity, calculated against universal standard of subjectivity
                + make calculation by looking towards how it would impune the subjectivity of the median average subject
                  + what does that actually involve
                    + look towards the median salary of an individual and the work done to fulfil that mandate and then have that as the standard
                      + go back to comparing the theif and victim
                        + balancing the impedence of subjectivity, to do this you consider the effect on an individuals capacity to achieve a good life
                          + which is subjective and unknowable by others
                            + what about these pensions is valuable, and what have they lost becuase of the theft
                              + they have been disrespected to the point in which they would suffer great material loss/not being able to send children to education
                                + difficult to quantify but not impossible, look towards the relationship to happiness these things have towards average individual
                                  + happiness in what sense?
                                    + its about how much freedom you have taken away from them
                                      + murder for fun takes away freedom more than manslaughter
                                  + interpersonal comparison of utility
+ democracy as a right
+ legal institutions should make necessary a given level of wellbeing
+ who's stick is it?
+ up to the institution
+ justify the state
  + embodyment of subjectivity of all individuals
    + institutional rationality as it pertains to law
      + rationality can only be institution through mutual engagement towards certain ends of certain parties that leads to an institution

* Footnotes

[fn:1]https://www.wikidata.org/wiki/Q336 (https://archive.ph/Blr6n)

[fn:2]https://www.merriam-webster.com/dictionary/science (https://archive.ph/TQoHB)

[fn:3]"Ethics" is derived from the ancient greek ēthikós (ἠθικός) [sounds like "theek hoes"], meaning "relating to one's character." A man cannot have a character if he is dead.
