#+title: Free Will vs Determinism

* Notes
** The Meaning of Volition
+ the meaning of an action being free is that it was selected from one or more alternatives that were possible under the circumstances, and where the difference was made by a mans decision.
  + the choice is between whether to be conscious or not---reality does not force itself upon your mind, simply waiting for reality to grant you the truth would be fruitless. Your mind has to do something to grasp reality.
  + The conceptual level is not automatic, man has the choice whether to think or to evade.
  + The perceptual level is automatic, you have no choice to not see, you merely have the choice whether to consciously integrate that which you are seeing
+ evasion means actively avoiding the integration of facts on the premise that if one simply refuses to acknowledge A it will cease to be
  + it is not merely passively not integrating, it is deliberately blinding yourself to the truth
** The Epistemelogical Self-Defeat of Determinism
+ epistemology is "how do I know?" Which requires /knowledge/, i.e. beliefs that have been /validated/, logic is the method of validation and thus is involved in the method of acquiring knowledge
+ to ask for validation of any knowledge is to accept the pre-suppositions of epistemology.
  + One such pre-supposition is that mans knowledge requires validation in the first place
  + mans knowledge can require validation only if consciousness is not automatic---if consciousness was automatic man would simply possess the thoughts that he possesses validation be-damned
  + an automatic consciousness has no need of nor no ability to engage in any method of validation.
+ if determinism is true then the determinist is pre-destined to accept determinism
  + how then does the determinist hope to validate determinism?
  + the factors that caused him to be a determinist are clearly not infallible, because those same laws caused other people to not be determinists, so he must accept that man can think in error
  + so the determinists mind is not automatically attuned to reality and the determinist claims that he has no choice over what he believes such that he could not validate any belief that he holds---the determinist claims that he cannot deliberately choose reality over fantasy.
** Free Will and Causality
+ Causality is broader than the mechanistic notion of antecedent factors determining descendant factors, such that if you know the antecedent factors this is sufficient to know the descantant ones
  + Causality means broadly that what a thing is determines how it behaves, its behaviour is caused by its identity
+ compatibilism is fine if determinism just means causality, not if determinism means that volition does not exist
** general notes
+ determinists will say that not everything in the physical world is like clockwork, citing quantum mechanics
+ determinists will also say that we cannot predict human action, they merely assume that we could do it with enough information
+ looking in the wrong place for free will
  + it is not primarily about content---eat vanilla or chocolate ice cream
  + its about the processing your mind engages in---you can think (focus your mind) or not
  + its not "am I going to choose A or B," the choice is over the antecedent thought or lackthereof which will determine how this decision is made
    + perhaps you pick A because you are considering all of the relevant facts that have been previously integrated or B because you are placing some out-of-context consideration /above/ those facts (evasion), or because you have failed to previously integrate those facts (drift)
+ there are two aspects to focus
  + energy being put into the focus, effort, control
  + the purpose to which the focus is put, either;
    + deal with the facts, come what may
    + place some consideration above the facts (active evasion)
+ the Objectivist stance on free will is that you can choose the rationality or irrationality of your focus, and whether you focus or drift
+ it makes no sense to speak of free-will or determinism being "proven" as the entire notion of proof pre-supposes free-will---it pre-supposes that man can be in error and requires a process of validation
* flow
+ [X] is your position one that man lacks volition or merely a scepticism about man having volition?
  + no adequate basis for free will
  + focus vs drift
    + control, letting is the operator of free will
      + ability to actively engage your mind or not
        + that state is one that can be described, the operator is the choice---the abi
+ [X] it makes no sense to speak of free-will or determinism being "proven" as the entire notion of proof pre-supposes free-will---it pre-supposes that man can be in error and requires a process of validation
+ [X] determinist hypocrisy:
  + determinists will say that not everything in the physical world is like clockwork, citing quantum mechanics
  + determinists will also say that we cannot predict human action, they merely assume that we could do it with enough information
+ [X] epistemelogical self-defeat:
  + to ask for proof of anything or to claim that language is possible pre-supposes that man can hold erroneous beliefs
  + on the determinist view a man will simply hold whatever beliefs he holds with no ability to validate those beliefs---if conscioussness was automatic then a man would simply believe whatever he happens to believe validation be-damned
    + implies that on a deterministic perspecitve you cant change, that there is no ability
      +
  + the determinist must accept that man can think in error as the same deterministic laws caused free-will believers to believe in free-will
  + how can the determinist validate determinism on these premises?
  + the determinist claims that he cannot deliberately choose reality over fantasy
+ epistemology is dead if no free will
  + but then determinism cant be proven
    + simply hold
+ issue not that we have boundaries on what can or cant be true in the world if free will is the case
  +
+ the referant of a truth statement
  + truth
+ whether there are facts is the bedrock of epistemology
  + if there are no humans there are still rocks means that the facts that underpin our knowledge arent based on free will
    + sure, existence has primacy
      + idea that an autonomous agent cant be either or true or false based on underlying conditions not free will---fill in free
        + determined being can collect sense data
          +
+ hunger is physiological and can be a desire
  +
+ desires not automatic
  + brought about by thought
    + even if came to think a desire of not eating
+ action has to be rooted in desire else no action, no desires means no action
+ "limit on volition"
  + only will in ways that you already desire
+ sense data that we receive as hunger is not the desire in itself, but directly corresponds to the stored value that we then use in a scale of values
+ desire to eat didnt come from nowhere
  + desire to climb a mountain came from seeing a mountain
+ chicken and egg, desire constrains volition
  +
+ hunger as a perception
  + biological hunger isnt an emotion
+ causal nature of the universe being something that can be observed and we can have knowledge of
  + free will outside of this---no!
    +
+ the will functions is its a part of the conscious experience where we have underlying desires, the will takes into consideration with other components of the mind and is the mediator between these desires and what comes out at the other end
  + we can have a desire for congruency with reality which would give an identical outcome to "libertarian" free will, immune to causality
    + "mediation" is a stolen concept
+ there is a concept of free will that he's OK with
  + presentation comes from straussen---will mediator of desires, volition is the mediation
    + the will is a will module that we pump inputs into and it evaluates a hierarchical
      + can it vary its output?
        + if its deterministic the epistemelogical problem remains
          + can be explained by the components, by their nature, this does not negate the point!
+ the wants and desires are operators in the mind
  + only do the things you have a want or desire to do
    + wants and desires built from prior thought/evasion!
      + emotions come after your thoughts, they are not arbitrary
+ desire to eat food comes from biological impulse and pro-life
  +
+ in order to want to change you have to want to want to change...
  + not the case, it is not based on whim, it is based on the action of will
    +
+ at the limit for immortal beings, if we have many thoughts will we not wind up in unbreakable patterns
  + why?
    +
+ AI and knowledge
  + some writing that LLMs are on the edge of knowledge
    + perhaps some future AI could have volition
    + these AIs have access to a wide array of sense data and are constrained by their construction
      + how can they know to trust their sense data?
    + the AI is preloaded with millennia of human philosophy
      + massive head-start!
+ stolen concept of truth in cartesian doubt
  + error is defined as non-truth
    + if we can come to error we can come to truth
+ cant come to error or truth
  + "there *is* a concept of truth which doesnt corresspond to anything we have access to"
    + is that true?
+ what if out of your own control you held a desire to pursue knowledge, you have the capacity for validation
  + why cant validate?
    + validation requires that you can choose reality over fantasy
      + there is no meaning of validation on this view
+ laws of identity and non-contradiction are axiomatic---this means that you must accept them as true in thought, even in disputing them
  + not deductive
+ the way I was talking about them was if a platonic knowledge of them is required
+ how we engage with these concepts is a non-perfect method
  + stolen concept
+ agreeing to some extent that pure knowledge is something we dont have access to
  + dont know what pure knowledge is (reality as it really is? no such thing as reality as it really isnt)
    +
+ walk through the criticism
+ free will and causality
  + compatible
+ is will separate from the antecedent
+ everything in the mind can be boiled down to physical components
  + I dont disagree
  + if we have a mind
+ basal components of the brain interact through mechanistic causal interactions even if we cant yet adequately explain all of them
  + factors that determine choices
  + mind is material
    + if there will be consistency if a certain signal enters a certain area with enough information we can predict
+ chicken and egg of desires, rationalist could explain it away with a priori values
  + tabula rasa you cant come to action, nothing to motivate you
    + develop conceptual faculty
      + values are what direct thought
        + no
  +
