#+TITLE:Ancaps are anarchists
#+AUTHOR:LiquidZulu
#+HTML_HEAD:<link rel="stylesheet" type="text/css" href="file:///e:/emacs/documents/org-css/css/org.css"/>
#+OPTIONS: ^:{}
#+begin_comment
/This file is best viewed in [[https://www.gnu.org/software/emacs/][emacs]]!/
#+end_comment

* Notes
** His response video https://www.youtube.com/watch?v=A2yjOWUUanI
*** Mutual Profit in Trade
To clarify my position with respect to mutual profit in trade, I mean exclusively /voluntary/ trades, and I am speaking in the ex ante sense. So if I trade $5 for a hotdog you know that I must have valued the hotdog more than the $5 and conversely the hotdog vendor must have valued the $5 more than the hotdog. If these value scales were not present then the trade would not take place as nobody wants to trade for something they value less. It is possible that after eating the hotdog I didn't enjoy it as much as I expected I would, and thus I regret the trade. This is a loss in the ex-post sense, my predictions did not pan out.

Applying this to the case of feudal europe, these were not voluntary trades, its hard to call them trades at all, and I agree that these are in fact not mutually beneficial.
*** Georgist reductio
For simplicity I shall call all natural resources "land." The georgist take is that if someone controls all the land this is necessarily not a free society, there are some issues with this:
1. this is not even close to something we would expect to occur, as technology advances we can make ever more efficient use of land and we can access more of it in the first place. With the advent of private space travel it will not be long until we are capable of using all of the land in the solar system, which is an unfathomable quantity.
2. even taking it as a reductio ad absurdum -- namely, taking it to be a test of ones ethics rather than an economic argument -- there is still no aggression occurring. Picture two people on an island, Crusoe and Friday, assume that the island is all there is. Crusoe picks and eats a berry that Friday wasn't even aware of. How can it be said that this action is aggressive towards Friday, Friday clearly didn't own the berry, thus he gets no say over it. Moreover as Friday didn't own the berry Crusoe has no duty towards Friday with respect to the berry, which we can syllogise as follows:[fn:1]
   1. person A has a right toward person B that person B not do X if and only if person B has a /duty/ toward person A /not to/ do X;
   2. person A has a right toward person B that person B does X if and only if person B has a /duty/ toward person A /to/ do X;
   3. person B has /no duty/ toward person A /not to/ do X if and only if person B has a /liberty/ toward person A /to/ do X;
   4. person B has /no duty/ toward person A /to/ do X if and only if person B has a /liberty/ toward person A /not to/ do X.
   5. because Friday is not the owner of the berry, he has no right toward Crusoe with respect to the berry, and Crusoe therefore has no duty toward Friday to not pick or eat the berry.

Moreover, to say that it is not a voluntary trade to buy water from me when I am the only one with water is flawed. Why is it that when other people don't have water that this is my problem? What if two people were selling water, would that still be involuntary? What if 4 people were? What if 100 people were? Is it always involuntary to sell things? If not, at what point does it become involuntary? Further, I bring my sex disease reductio; I have a disease where I will die if I do not have sex with a woman, would a prostitute be coercing me? Would I be allowed to force a woman to have sex with me? If it is true that the water salesman is coercive and that you may seize water, then it must also be true that prostitutes coerce me and that I may rape them.
*** Abundance of natural resources
If by abundance quibbles is meaning that the land must become general conditions of human welfare, that is to say, that they must not be scarce then his anarchism requires a world that cannot occur. It is a fact of reality that men must employ scarce means to attain ends, if these means were not scarce man could not act, as he would already be perfectly satisfied. This is true for means such as time, but also for land. You cannot will that a given resource will become infinite, no matter how hard you try, there will always be scarcity in land, if this were not the case the georgist worry of a man owning it all would have an extra nail in its coffin.
*** Unjust hierarchies
Quibbles says that wage labour and owning things are unjust hierarchies because you cannot say no to it, this is false. I am fully capable of not getting a job and instead living for myself, but I would not like this situation, I prefer the comfort of a regular job, and I am more productive in this than I would be otherwise. Further, it is incoherent to say that owning things is unjust because to determine justice you need to know who owns what. Any legal system requires a property system.
* Flow
+ damming up river
  + filtration is work
    + all goods require processing
      + pay society for the water as land
        + justification for LVT
          + stolen from everyone else
            + if you cant divide out the land and the capital good
              + payed for through govt
                + how are they paying
                  + govt decides LVT
                  + carbon divident
                    + how much are paying
                      + paid to govt
                        + 30/tonne
                          + whatever gets the most money possible
                            + union of the people decide where money goes
                              + equal distribution through UBI
                                +
                    + fire dept public
+ feudalism means you own all the land in a given area
+ historically abundance of air
  + general conditions of human welfare
    +
+ for strict anarchy, on aggregate the only thing that can be the basis for trade is labour and capital
  + post scarcity for anarchism
    + definition of anarchism
      + without ruler
        + post scarcity for no ruler
          + someone owns all land in a given region, to live there you need to pay rent to the man, pay in food, expect the residents to provide military aid
            + there exists infrastructure where no
+ LVT
  + quantify the value of the property
    + who's value
      + objective value
        +
+ govt needed to stop crime
  + competing firms vs monopolies
    + when monopolies superior
      + economies of scale, dangerous implications for someone owning a road
        + what are the criteria
          + buying it at point of use, mean exploitation, when you dont have an option. Emergency room, fire
* Footnotes

[fn:1]Lukasz Dominiak. 2017. “The Blockian Proviso and the Rationality of Property Rights.” Libertarian Papers. 9 (1): 114-128. ONLINE AT: libertarianpapers.org.
