#+TITLE: Economics/Ethics of Anarcho-Capitalism

* Notes
** Childrens Rights
*** Definitions
Children are those self-owners who cannot yet engage in human action but may at some point in the future. The relevant point being that they therefore cannot express their own will.

Guardians are the executors of the childs will
*** Areas of potential conflict
1. Conflicts between a child and his guardian over his own autonomy
2. Conflicts between a guardian and someone he claims to have done harm to his child
3. Conflicts between a former child and someone he claims to have harmed him
4. Conflicts between two potential guardians over the claim to a child
***
** Homesteading
Homesteading is defined as the original appropriation of a scarce nature-given good. Ownership is different to mere possession, which implies that late-comers cannot be the owners of a property, if they were then we would be back to mere possession which contradicts ownership not being possession.

Furthermore it would be impossible to do anything if late-comers had an equal say over the use of a property as the first-comer, as before the first-comer could begin using the nature-given good for anything he would have to wait for permission of every late-comer, which is a set of indeterminate size that may include people who are yet to be born.

Abandonment of priority to the first-comer would also run contrary to the conflict-avoiding nature of argumentation and the very purpose of property rights in the first place. This is because priority given to the late-comer is by definition a conflict-initiation norm---it is a norm that supposses those who are initiating the conflict get priority in a dispute over property rights.
** What are rights
** The Necessity for Law and thus Property Rights
#+begin_quote
As long as scarcity and hence potential interpersonal conflict exists, every society requires a well-defined set of property rights assignments.
#+end_quote
--- Hans-Hermann Hoppe, /The Ethics of Liberty/ p. xiii
+ the law assigns property
+ by the very fact that one is engaging in any ethical deliberation (or any deliberation at all), it is implied that one need concern oneself with scarcity, at the very least of the means implemented in the deliberation, and of appropriation, at the very least of the means one must appropriate to make the ethical deliberation.
*** The purpose of a human ethic
#+begin_quote
In fact, Rawls, to whom the philosophy profession has in the meantime accorded the rank of the premier ethicist of our age, was the prime example of someone completely uninterested in what a human ethic must accomplish: that is, to answer the question of what I am permitted to do right now and here, given that I cannot not act as long as I am alive and awake and the means or goods which I must employ in order to do so are always scarce, such that there may be interpersonal conflicts regarding their use.
#+end_quote
--- Hans-Hermann Hoppe, /The Ethics of Liberty/ p. xiv
+ cannot act, and hence remain alive, without the use of scarce means, that scarcity raising the possibility of conflict over those means
+ A human ethic has 2 properties it must satisfy:
  1. universalisation---applies to all mankind
  2. assures the survival of mankind (no point in concerning yourself with a human ethic if no humans are alive)
**** Argumentum e Contrario
If it is not the case that a person A was the owner of his body and all goods appropriated by him two possibilities remain:
1. another person, B, is the owner of A and all goods appropriated by A
2. all things are universally co-owned, A and B are equal owners of each other and all goods aquired by either party.

(1) fails on the grounds of not being a universal ethic---it describes a society of two distinct classes; humans and sub-humans

(2) fails on two separate grounds:
a. it would lead to the extinction of humanity as in order to act one would have to ask everyone else for permission to act, which is itself an action, meaning no action could occur.
b. co-ownership itself is impossible, as it cannot handle disputes over the co-owned means.

** What is science
Science refers to a systematic enterprise that builds and organizes knowledge, and the set of knowledge produced by this enterprise.[fn:1]
*** Definitions
**** Merriam-Webster[fn:2]
1.
   a. knowledge or a system of knowledge covering general truths or the operation of general laws especially as obtained and tested through scientific method
   b. such knowledge or such a system of knowledge concerned with the physical world and its phenomena (ex:natural science)
2.
   a. a department of systematized knowledge as an object of study (ex:the scicence of theology)
   b. something (such as a sport or technique) that may be studied or learned like systematized knowledge (ex:I have it down to a science)
3. a system or method reconciling practical ends with scientific laws (ex:cooking is both a science and an art)
4. the state of knowing---knowledge as distinguished from ignorance or misunderstanding

** Argumentation Ethics
*** What is argumentation
Argumentation is an interaction wherein two or more parties assert premises in support of two or more contradictory conclusions, with the goal of each party being to find what the correct conclusion is. Argumentation is specifically the method of solving disputes over claims of truth through the use of peaceful means, that is one tries to convince their interlocutor through the force of their argument, not by aggressing upon them.

The ideological salesman is in the business of persuading his opponents of his own conclusion, without paying any mind to what the truth of the matter is.

*** Ethic only applies during argumentation
+ inconsistent system of ethics, therefore false
  + argumentation does not turn an irrational animal into a rational one (a person)
Argumentation must take place between people, i.e. rational animals or actors. The fact that B deciding to engage in argumentation with A does not turn A into a person where before he was some beast incapable of action, it follows that this is an inconsistent system of ethics---in one moment the adherent asserts the ethic of liberty and the next some negation of it. Inconsistency is by definition contradictiory---to dispute this is to say that one may remain consistent in the ethic of non-aggression where they only aggress on a person in one location in spacetime but dont aggress on others in different locations in spacetime, which is an absurdity.
* flow
+ quality of life higher with taxes
  + why just
  + time preference
  + world happiness standard
  + life expectancy goes up in spite of govt growing
    + research that wouldnt happen otherwise
      + investing in what people dont want
        + heart disease research
          + any investment most people dont want to spend their money on electricity
            + entrepreneurs might if they expect that it will help people
              + natural selection of entrepreneurs
                + electricity---what would have been made otherwise
                  + making progress in things that people do not want
                    + no use to anyone today---so lower time preferences
                      + never see these discoveries outside of govt
                        + capital development
                          + oil subsidies
                            +
+ individuals cant make roads with rules
+ meteor after more humans
  +
+ govt funding doesnt work but did work in the case of oil
  + it works, but to what end?
    +
+ who decides the one project?
+ people can bring corpos to court for dirtying their laundry
  + my system impossible
    + iceland courts
      + sounds just like american legal system
        + the natural law ethic is simply correct, it has nothing to do with consequences
          + "which one has the more fair outcomes"
            +
+ dont care about the truth of morality
  + is something moral because
