#+title: Strategy Debate

* Notes
** The Role of Philosophy and Psychology in History
*** The Philosophy of History
+ the philosophy of history is concerned with the question of what caused men to act in the ways that they did in the past
+ theories of the philosophy of history:
  + Marxist economic theory of history---productive and economic factors are the real source shaping all human action throughout history, philosophy and ideology are irrelevant
  + St Augustine---God did it
  + Thomas Carlisle, the great man theory---a few outstanding individuals throughout history are the causes that shape everything
  + sceptic---there are no causes for the way that men have acted, its all chance
  + ecclectic---some of all of the above
  + objectivist viewpoint---the philosophic interpretation of history. Philosophy is the decisive causal factor; the philosophy of any given age is the decisive causal factor shaping the actions of men and the events which take place.
*** The Psychological Theory of History
+ the psychological theory of history---explain peoples behaviour throughout the centuries in terms of the psychology of the actors
  + its obvious that most people have no coherent, articulate philosophy; philosophy to most people is just a smattering of vague ideas. So its questionable whether they even have a philosophy, but they obviously must have a psychology.
  + people act on the basis of their psychologies; they act on their motives, their desires, their emotions, etc.
  + psychological theory of history on nazism
    + take some nazi leader, hitler, goering etc; you do not have these men unless there exists men with a tremendous power lust, a tremendous desire for domination, etc, and you couldnt have their mass following without a nation of people who felt the need for dependence.
      + on its face this is true. These factors must have existed and they are required for the events to take place as they did, but they are not the originary factors. These psychological desires and motives are borne out of a mans particular philosophy.
  + philosophy is at most a rationalisation for the underlying psychological motives
*** The Error of the Psychological Theory of History
+ There are indeed psychological factors which are indispensable to the workings of history, but what is the source of these psychological factors? What is their cause?
  + it cannot be that any specific psychology emanates from human nature as such because the specific motivations and desires of men differ.
  + And on this view why would it be that there are seemingly trends in the psychologies of men? Even if mens psychologies could differ given their nature why would there be eras of different prominent psychologies?
  + Fundamentally the psychology of individual outliers is not relevant, what causes a psychology on such a scale as to be a factor in shaping history?
  + Certain emotions, certain feelings are the cause of these psychological traits.
  + The source of emotions is ideas. The distinction between an emotion on the one hand and a sensation on the other is that a sensation can be transmitted by strictly physical means.
    + If I pinch a mans arm it does not make a difference whether he is an Aristotelian or a Platonist, he will feel the sensation of pain.
    + On the other hand his emotional response to this may be entirely different based upon his ideas. If a libertarian sees me robbing a factory owner at gunpoint he will have an entirely different emotional reaction to this than a communist would.
  + The only ideas which pertain to fundamental ideas and thus can pervade an entire society are philosophical ideas.
+ How would philosophy breed a culture-wide psychology of (for instance) dependence?
  + indirectly---shaping the institutions of a country.
    + philosophy shaping a political system which is statist will result practically in the average man having less and less control over his own life, more dependence on the government. By all of the innevitable crises inherent in such a system the man will feel less in control less able to shape his life and wellbeing and thus feel more dependent on others for his life.
  + directly---by the explicit statements of its intellectuals.
    + the intellectuals spend their time degrading the individual, his mind is helpless, he cannot know anything, thinking is untrustworthy, there are no answers, there are no absolutes, etc. A mans life under such a system tells him that he must be dependent on a group for survival and all he ever hears is that he must be dependent on a group for survival.
+ A philosophy which shapes a free society would result in a society which requires men to think for themselves, to be independent, to work for their own sake and for their own happiness, and as such this is what men would learn to do.
** General
+ The split is one of the psychological vs the philosophical theory of history.
  + On the psychological theory it is of the utmost import to change the psychological makeup of the masses of men because this is the fundamental cause of their actions.
  + On the philosophical theory changing the masses are largely irrelevant. This is because they are not thinkers, they are not philosophers; they have no choice but to simply accept whatever philosohpy it is which is prominent within their society---this philosophy must have come about from the thought of a relatively small set of philosophers whose works propagate out through the education and the culture.
+ psychological theory of history is that psychological desires are the cause of mens actions, these desires are fundamentally derived from emotions, emotions are derived from thoughts
  + what makes emotions distinct from sensations is that sensations are caused by purely physical means---if you poke either a marxist or a libertarian with a needle they will feel the same pain sensation, if you rob a factory owner (single physical event) a marxist and a libertarian will have completely different emotional responses to this stimuli, due to their differing ideas
+ A statist philosophy, i.e. a philosophy of dependence will indirectly shape society by shaping institutions to be statist which will cause various crises thus making men feel less in control and more dependent.
  + and it will shape society by having intellectuals constantly telling men that they are impotent to be individuals that they must be dependent on groups that they have no worth.
* flow
+ black pill---libert society will never come about
  + regardless of the ethics people want others to be forced to do things
    + psychological theory of history
+ philosophy of history---philosophical vs psychological theory
  +
+ normal people determine the course of history
  + disagree, they do not promlegate philosophy
+ focus on intellectuals
  + most people dont think about philosophy
    + they borrow their philosophy
      + neither ideas nor philosophy comes prior
        + 50% of behaviour can be predicted by genetics and 50% by environment
          + normal people are pre-disposed to following
            + cant be based on nature, because the general psychology changes, and it differs between men, so it cant be based on their nature
+ psychology does vary between individuals, not fundamental like action
  + but if it varies then it cant be based on the nature of man as such
    + did mens brains change in different eras of different societal trends? Was the early medieval brain different to the post-scholastic brain?
      + if it was individual differences in brain makeup it should be basically random
        + the trends need to be explained
          + pre-disposed to cancer but dont go into sun, pre-disposed to statism but there are non-statist societies
            + early US did end up in a state---20th century corruption after the enlightenment, this is explainable on the philosophical theory
+ what causes certain philosophies to become prominent?
  + Plato vs Aristotle -> christianity
  + Aquinas succeeds -> enlightenment
  + post-enlightenment philosophers exploited mistakes made before
+ people swayed by the "so what"
  + he who has a why can endure any how
    + midwit only cares about the so what, but not the intellectuals
+ "cross cultural"---because there is no rational culture
+ return to fundamental point---emotions are not primary!
  + ideas and emotions simultaneous---very young children dont have ideas
    + they have a primitive philosophy insofar as they have ideas
      + hurt=bad is a sensation, not an emotion, emotions occur on the conceptual not perceptual level
        + pavlovian conditioning,
          +
+ emotion partly to do with your physical makeup
  + disagree, emotions are purely not based upon physical sensations
  + automatic means its part of the sensation
    + no difference between reflexive disgust of rotting flesh and reflexive feeling of pain
    + reflexive emotion is internal whereas sensation is about something external---the reflexive emotion is also caused by something external
      +
+ initial emotions would mean emotions which were borne out of purely physical stimuli, which makes them sensations
  +
+ people have emotional connection to the state, they have an innate physical sensation which drives them to the state
  + then why dont all men have this
+ average person has a sensational disgust of freedom
  +
+ what determines which topics a man is pre-disposed to evade on?
  + all people have a desire to evade on a topic where they have more satisfaction evading than thinking
    + then why do men ever integrate uncomfortable truths?
      + people aim to integrate uncomfortable truths becuase they expect greater satisfaction later
        + this expectation is caused by thought or evasion
      + people dont integrate uncomfortable truths, its uncomfortable in retrospect
  + how do we determine this to be the case?
    + normal people derive satisfaction from knowing that people they dont like get hurt
      + this is only so if they evade, they derive satisfaction from the opposite if they think!
        +
+ dont come to ideas because they are malicious---I agree!
+ cant be losing faith in horrible regime---medievals
  +
+ how do we get to public education?
+ not a problem of incentives
  +
+ right sectarianism---diluting principles
  + desantis
    +
