#+TITLE: Argumentation Ethics

* Main body
Hoppe's Argument from Argument, which is the foundation of his Argumentation Ethics has long been opaque to my eye. It always seemed to be a large word-salad of sorts that I just sort of took on faith that its probably true in some way. This has, in my view, been the result of a common problem amoung our great thinkers---that they are excellent at coming to novel and incredibly impactful theories, but they lack the related ability to communicate these deep philosophies to the lay person.

After an extrodanary amount of reading on and watching lectures about the topic I have finally come to what I think is an interpretation that loses nothing from the source material, whilst being comprehensible on a first listen.

[slide]First I shall discuss what exactly an argumentation, also called a dialectic, even is. [slide]Argumentation is defined as an interaction wherein two or more parties assert premises in support of two or more contradictory conclusions, [slide]with the goal of each party being to find what the correct conclusion is. [slide]Argumentation is specifically the method of solving disputes over claims of truth through the use of peaceful means, that is one tries to convince their interlocutor through the force of their argument, not through force of violence.

[slide]I would also like to briefly go over what argumentation is not. [slide]It is not simply about convincing others that you are correct without paying any mind to the truth of the matter---that manner of speech is that of the ideological salesman, who simply wants to be seen as being correct. [slide]True dialectic is about reaching a synthesis, you articulate your premise to your interlocutor as an invitation for them to test its rigour. If they disprove your claim, you have both gained information as you now both know where the truth is not, if you instead prove your claim you now both know where the truth is---no matter what you gain knowledge.

[slide]It should also be noted that argumentation is not simply free-floating propositions with no connected proposer, it is a human action requiring the use of scarce means towards the end of finding the truth of the matter.

[slide]Further it has to be stated that argumentation cannot exist in a normative void, [slide]that is there are certain norms that are presupposed in the very act of argumentation. [slide]For instance one could not argue that argumentation is pointless, this would be called a dialectic or performative contradiction. Because to argue the norm that argumentation is pointless would be contradicted by the very positing of it---[slide]hence we denote this as a dialectic falsehood.

We hence revisit our definition of argumentation to see if we can find a norm more relevant to libertarian ethics. We noted that argumentation was a peaceful interaction, let's quickly make that more concrete---what would it mean to say that argumentation need not be peaceful. Well it would mean that you don't care about the truth, because you would be choosing to violently attack your opponent to solve the dispute rather than allowing them to present counter-arguments. Therefore violence must not be a valid move in an argumentation. We now recognise that the set of peaceful actions may be reframed as the set of non-aggressive actions---it is specifically those actions that initiate conflicts that are not peaceful. Therefore conflict avoidance must be another norm presupposed in the act of argumentation.

From this we can come to a dialectic truth; that conflicts ought to be avoided---but it is this that is the very foundation of modern Rothbardian Natural Law Theory. Hence no ethic could possibly be proposed that would contradict Libertarianism, as the very proposal of this ethic would be a dialectic contradiction.

* Counterarguments
Now, this theory due to its often very nuanced presentation, has attracted many critics including within libertarianism; Bob Murphy and Gene Callahan being prime examples. So I would like now to go over some of the more popular counterarguments to the argument from argument.

** [slide]AE only applies during the course of an argument
The first is that this argument applies only in the course of an argumentation, that while its true that I cannot argue for an ethic that murder is good say, it has nevertheless not been proven that murder is bad outside of an argument---I would not contradict myself to go about arguing then simply not arguing whilst I'm on a murder spree.

This counterargument fails on a number of grounds. First if it is true that the conclusions reached in an argumentation only matter during the course of that argumentation the same could be said of all conclusions, not only those related to the argument from argument. Its as if I were to grant that it is true that voluntary trades are mutually beneficial but only when we are alctually arguing and that after the argument I revert back to believing in the contrary, that they are not mutually beneficial. This would be the complete abdication of truth.

Second, when used by someone arguing a dialectically false ethic, even if we grant them that their ethics can change inside and outside of an argument, this leaves them with the position of stating an inconsistent and therefore contradictory ethic. It's as if I were to say that murder is bad in one part of spacetime but good in another---I am simultaneously taking the opinion that murder is both good and bad.

** [slide]AE only applies to the body parts required for an argument
The second counterargument is that argumentation ethics only precludes me from being violent towards the body parts that one is using in the course of an argument, it may be true, the sceptics claim, that I would contradict myself by cutting my interlocutors tongue out, but I would not by breaking his legs. This counterargument misses the mark in that Hoppe's argument is not about which body parts are being used, its about solving the dispute through peaceful rather than violent means. It is certainly true that breaking a mans legs is violent, therefore this is an impermissible move in an argument.

* [slide]Other notes
To finish up I would like to go over a few other notes on this topic, to hopefully round out your understanding. [slide]First each participant in an argument must be entitled to exclusive control over their own body, they cannot simply be a mouthpiece for someone else. Imagine if A and B are wanting to argue but A has total control over B. This would mean that A is really just speaking to himself as B would not be able to say anything that wasn't pre-ordained by A. Further imagine if C has total control over B, still B would not be arguing with A, rather A would be arguing with C.

[slide]Further, I wish to clarify in what sense this argument gives us "truths." We did not derive from some apodictically true axiom that you ought not aggress, its not analytically true, but it is dialectically true which is another, objective, foundation for truth. As any other ethic would be contradictory and thus false.
* [slide & for each]Further study
+ [[https://www.youtube.com/watch?v=WqO54eWt4Ws][Hans-Hermann Hoppe’s Argumentation Theory of Ethics | Łukasz Dominiak]]
+ [[https://www.youtube.com/watch?v=b8UE3QAV8JM][Hans-Hermann Hoppe - Ethics of Argumentation (PFS 2016)]]
+ [[https://www.researchgate.net/publication/293200578_Argumentation_Ethics_and_The_Philosophy_of_Freedom][Dun, Frank. (2009). Argumentation Ethics and The Philosophy of Freedom. Libertarian Papers. 1.]]
+ [[https://www.stephankinsella.com/2015/08/hoppes-argumentation-ethics-and-its-critics/][Stephan Kinsella, "Hoppe’s Argumentation Ethics and Its Critics"]]
