#+TITLE: Anarchy vs Minarchy Debate

* Notes
** His response
*** How much rights enforcement does this quasi-state provide to each individual?
He responds by listing what rights it would provide, but not how much rights enforcement it provides, those rights being:
+ right to defense
+ peaceful protest
+ freedom of speech
+ right to vote
+ right to referrendum
+ right to life
+ right to own firearms
+ right to use whatever currency they wish
+ right to own property
+ right to marriage
+ mirranda rights
+ freedom of movement

His summary is "any action that an individual can take that doesnt harm another individual [is a right]"
*** How do you expect such an entity to form and to maintain itself?
His answer is; "look at the average income of the citizens and the minimum amount the state requires to function and tax accordingly."
* flow [1/7]
+ Are you an anarchist? [2/3]
  + [X] do people have the right to aggress unto others?
  + [X] can people delegate rights they do not have?
  + [ ] does the state have the right to aggress unto others?
+ [ ] is taxation theft?
  + if not in contract with the state
    + taxation isnt theft when you agree to pay the state
      + state provides protection from foreign powers
+ [X] Is the free market, or coerced monopolisation the best at delivering products and services?
+ [ ] Do you accept total free association?
+ [ ] How much rights enforcement does your state provide to each individual?
  +
+ [ ] How do you expect your state to maintain itself?
  + if you want to be a citizen the state makes a contract with you where you have to pay it a given amount of money
    + literally a covenant community?
    + "they consent"
      +
+ [ ] How do you expect your state to form?
+ [ ] Can you prove that your minarchist state will have superior outcomes to a total free-market?
  + hes gonna say about how NASA invented memory foam then the free market improved it
+ what would pr
