#+TITLE: Hopping Mad Libertarian Ethics Lecture

* Notes https://www.youtube.com/watch?v=kAOzjM5q4Dg
+ What is the upshot, does the argument give us a reason to care?
  + if you care at all about living which you do then you necessarily care about having a proper ethic for man. So seems pretty important to study that ethic
+ each party must have exclusive control because he has to come to a conclusion on his own to present as a proposition
* Kinsella on AE https://youtu.be/PgvQ-sRRwxc
+ either you own yourself or other people own you --- self ownership or slavery
+ certain norms are presupposed by the act of argumentation, so one could not possibly argue against these norms.
  + if you have two people come together to discuss what a just norm would be or what ethic we should be adopting you have necessary mutual recognition of self-ownership
    + the act of A arguing with B requires that both A and B make use of scarce means in the argumentation, therefore A must accept that B owns himself and the means that B must implement to argue and vice versa.
      + Trying to propose an ethic of slavery would be impossible, because if A attempted to propose a norm that A owns B, that would be incompatible with the fact that A has to recognise B's exclusive ownership over himself to allow B to argue
        + arguments are not just free floating propositions, it requires that both parties make use of their bodies and scarce means to communicate the propositions and to maintain their life.
+ there is nothing wrong with having norms and inserting those norms, you just cant sneak them in---be explicit in your normative presuppositions
* Theory of Socialism and Capitalism ch. 7
