#+TITLE:
#+AUTHOR:LiquidZulu
#+HTML_HEAD:<link rel="stylesheet" type="text/css" href="file:///e:/emacs/documents/org-css/css/org.css"/>
#+OPTIONS: ^:{}
#+begin_comment
/This file is best viewed in [[https://www.gnu.org/software/emacs/][emacs]]!/
#+end_comment

* notes
** The State is De-Civilising
*** Taxation is de-civilising
+ Taxation invariably runs counter to the natural tendancy of time preference to fall, as it disincentivises saving and production --- if I know that I will be robbed for producing or attempting to save I will have higher time preference
  + see [[Taxation is a means of the destruction of property][here]] for more info.
+ Taxation may even reverse the tendancy, that is, it may effect a tendancy for time preference to go up --- in effect pointing society down a path of de-civilisation towards bare subsistence living.
*** Taxation is a means of the destruction of property
+ Taxation is a coercive, non-contractual, transfer of definite physical assets, from their rightful owners who whilst in possession could have derived income from holding them, to some other person or group of people who can now derive income from holding them.
+ How did these assets come into possession of the original owner? Excluding prior taxation and noting that only those assets can be taxed that have not yet been consumed or had their value exhausted through acts of consumption (the tax man does not take away a mans garbage), there are three possibilities:
  1. The owner perceives some nature-given goods as scarce and actively brings them into his possession before anyone else takes this action --- homesteading
  2. The owner produced them through nature-aquired goods that he previously homesteaded --- production
  3. Through voluntary, contractual, aquisition from a previous appropriator or producer --- trade
+ Only through these methods is one capable of aquiring taxable assets.
+ From this it follows that any form of taxation implies a reduction of income a person can expect to receive from homesteading, production, or trade.
+ Since these activities require the employment of scarce means which could be used for consumption or leisure, the opportunity cost of performing them is raised.
+ The marginal utility of homesteading, producing, and trading is decreased and the marginal utility of consumption and leisure increased.
+ Accordingly, there will be a tendency to shift from the former means to the latter ones.
+ Thus, taxation, in its reduction of both present and future income for producers, effects a tendancy towards higher time preferences cetirus paribus.
** Rogue Agency Problem
+ in anarchy some rogue agency might not respect the NAP and might expand, doing awful things like taxing people and forcing arbitration and "protection" through them.
  + worst case scenario of anarchism is statism
* flow [0/4]
+ [ ] Are you an anarchist?
  + [ ] Jan v Bernie Method
    + [ ] do people have the right to aggress unto others?
    + [ ] can people delegate rights they do not have?
    + [ ] does the state have the right to aggress unto others?
+ [ ] is taxation theft?
+ [ ] Is the free market, or coerced monopolisation the best at delivering products and services?
+ [ ] Do you accept total free association?
